openapi: 3.0.3
info:
  title: Odoo Expense API
  description: REST API for managing employee expenses in Odoo
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://your-odoo-instance.com
    description: Production server

security:
  - bearerAuth: []

paths:
  /api/v1/expenses:
    get:
      tags:
        - Expenses
      summary: Get expenses list
      description: Retrieve a list of expenses for the authenticated employee
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          description: Number of records to return
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: Number of records to skip
          schema:
            type: integer
            default: 0
        - name: state
          in: query
          description: Filter by expense state
          schema:
            type: string
            enum: [draft, reported, approved, done, refused]
        - name: show_all
          in: query
          description: Show all expenses or current month only
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Expense'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      tags:
        - Expenses
      summary: Create new expense
      description: Create a new expense
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExpenseRequest'
      responses:
        '201':
          description: Expense created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  expense_id:
                    type: integer
                  message:
                    type: string

  /api/v1/expenses/{expense_id}:
    get:
      tags:
        - Expenses
      summary: Get single expense
      security:
        - bearerAuth: []
      parameters:
        - name: expense_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Expense details
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/components/schemas/Expense'

    put:
      tags:
        - Expenses
      summary: Update expense
      security:
        - bearerAuth: []
      parameters:
        - name: expense_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateExpenseRequest'
      responses:
        '200':
          description: Expense updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/v1/expenses/{expense_id}/delete:
    delete:
      tags:
        - Expenses
      summary: Delete expense
      security:
        - bearerAuth: []
      parameters:
        - name: expense_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Expense deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/v1/expenses/{expense_id}/attachments:
    get:
      tags:
        - Attachments
      summary: Get expense attachments
      security:
        - bearerAuth: []
      parameters:
        - name: expense_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Attachments list
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  attachments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Attachment'

    post:
      tags:
        - Attachments
      summary: Add attachment
      security:
        - bearerAuth: []
      parameters:
        - name: expense_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - file_data
              properties:
                file_data:
                  type: string
                  description: Base64 encoded file
                file_name:
                  type: string
                  description: File name
      responses:
        '201':
          description: Attachment added
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  attachment_id:
                    type: integer

  /api/v1/expense/reports:
    get:
      tags:
        - Reports
      summary: Get expense reports
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Reports list
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  reports:
                    type: array
                    items:
                      $ref: '#/components/schemas/Report'

    post:
      tags:
        - Reports
      summary: Create expense report
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - expense_ids
              properties:
                name:
                  type: string
                expense_ids:
                  type: array
                  items:
                    type: integer
      responses:
        '201':
          description: Report created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  report_id:
                    type: integer

  /api/v1/expenses/categories:
    get:
      tags:
        - Public
      summary: Get expense categories
      description: Public endpoint - no auth required
      responses:
        '200':
          description: Categories list
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  categories:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string

  /api/v1/expenses/vendors:
    get:
      tags:
        - Public
      summary: Get vendors
      description: Public endpoint - no auth required
      responses:
        '200':
          description: Vendors list
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  vendors:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Bearer token authentication

  schemas:
    Expense:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        total_amount_currency:
          type: number
        currency:
          type: string
        date:
          type: string
          format: date
        state:
          type: string
          enum: [draft, reported, approved, done, refused]
        payment_mode:
          type: string
          enum: [own_account, company_account]

    CreateExpenseRequest:
      type: object
      required:
        - name
        - total_amount_currency
        - product_id
      properties:
        name:
          type: string
          example: Business lunch
        total_amount_currency:
          type: number
          example: 45.50
        product_id:
          type: integer
          example: 123
        payment_mode:
          type: string
          enum: [own_account, company_account]
          default: own_account
        date:
          type: string
          format: date
        description:
          type: string

    UpdateExpenseRequest:
      type: object
      properties:
        name:
          type: string
        total_amount_currency:
          type: number
        product_id:
          type: integer
        payment_mode:
          type: string
          enum: [own_account, company_account]
        date:
          type: string
          format: date
        description:
          type: string

    Attachment:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        mimetype:
          type: string
        file_size:
          type: integer

    Report:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        state:
          type: string
        total_amount:
          type: number
        expense_count:
          type: integer

tags:
  - name: Expenses
    description: Expense management
  - name: Attachments
    description: File attachments
  - name: Reports
    description: Expense reports
  - name: Public
    description: Public endpoints
